# Generated by Django 5.0.4 on 2024-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('avg_rating', models.FloatField()),
                ('num_ratings', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
